<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        DB::table('products')->delete();
        
        DB::table('products')->insert(array (
            
            array (
                'id' => 2,
                'name' => 'Queijo',
                'ingredients' => 'Pão e Fatias de Queijo',
                'value' => '6.00',
                'type_id' => 2,
                'active' => 0,
                'created_at' => '2023-02-04 22:56:12',
                'updated_at' => '2023-02-04 22:56:12',
            ),
            
            array (
                'id' => 3,
                'name' => 'Misto',
                'ingredients' => 'Pão, Queijo e Presunto',
                'value' => '7.00',
                'type_id' => 2,
                'active' => 0,
                'created_at' => '2023-02-04 22:56:12',
                'updated_at' => '2023-02-04 22:56:12',
            ),
            
            array (
                'id' => 4,
                'name' => 'Hambúrguer',
                'ingredients' => 'Pão, Hambúrguer, Queijo e Salada',
                'value' => '8.00',
                'type_id' => 2,
                'active' => 0,
                'created_at' => '2023-02-04 22:59:02',
                'updated_at' => '2023-02-04 22:59:02',
            ),
            
            array (
                'id' => 5,
                'name' => 'X-Burguer',
                'ingredients' => 'Pão, Hambúrguer, Presunto, Queijo e Salada',
                'value' => '10.00',
                'type_id' => 2,
                'active' => 0,
                'created_at' => '2023-02-04 22:59:02',
                'updated_at' => '2023-02-04 22:59:02',
            ),
            
            array (
                'id' => 6,
                'name' => 'Americano',
                'ingredients' => 'Pão, Presunto, Queijo, Ovo e Salada',
                'value' => '10.00',
                'type_id' => 2,
                'active' => 0,
                'created_at' => '2023-02-04 22:59:02',
                'updated_at' => '2023-02-04 22:59:02',
            ),
            
            array (
                'id' => 7,
                'name' => 'Minuano',
                'ingredients' => 'Pão, Hamburguer, Ovo, Queijo, Presunto e Salada',
                'value' => '11.00',
                'type_id' => 2,
                'active' => 0,
                'created_at' => '2023-02-04 22:59:02',
                'updated_at' => '2023-02-04 22:59:02',
            ),
            
            array (
                'id' => 8,
                'name' => 'Queijo',
                'ingredients' => 'Pão e Fatias de Queijo',
                'value' => '6.00',
                'type_id' => 2,
                'active' => 1,
                'created_at' => '2023-02-04 22:56:12',
                'updated_at' => '2023-02-04 22:56:12',
            ),
            
            array (
                'id' => 9,
                'name' => 'Misto',
                'ingredients' => 'Pão, Queijo e Presunto',
                'value' => '7.00',
                'type_id' => 2,
                'active' => 1,
                'created_at' => '2023-02-04 22:56:12',
                'updated_at' => '2023-02-04 22:56:12',
            ),
            
            array (
                'id' => 10,
                'name' => 'Hambúrguer',
                'ingredients' => 'Pão, Hambúrguer, Queijo e Salada',
                'value' => '8.00',
                'type_id' => 2,
                'active' => 1,
                'created_at' => '2023-02-04 22:59:02',
                'updated_at' => '2023-02-04 22:59:02',
            ),
            
            array (
                'id' => 11,
                'name' => 'X-Burguer',
                'ingredients' => 'Pão, Hambúrguer, Presunto, Queijo e Salada',
                'value' => '10.00',
                'type_id' => 2,
                'active' => 1,
                'created_at' => '2023-02-04 22:59:02',
                'updated_at' => '2023-02-04 22:59:02',
            ),
            
            array (
                'id' => 12,
                'name' => 'Americano',
                'ingredients' => 'Pão, Presunto, Queijo, Ovo e Salada',
                'value' => '10.00',
                'type_id' => 2,
                'active' => 1,
                'created_at' => '2023-02-04 22:59:02',
                'updated_at' => '2023-02-04 22:59:02',
            ),
            
            array (
                'id' => 13,
                'name' => 'Minuano',
                'ingredients' => 'Pão, Hamburguer, Ovo, Queijo, Presunto e Salada',
                'value' => '11.00',
                'type_id' => 2,
                'active' => 1,
                'created_at' => '2023-02-04 22:59:02',
                'updated_at' => '2023-02-04 22:59:02',
            ),
            
            array (
                'id' => 14,
                'name' => 'Mr. Frango',
                'ingredients' => 'Pão, Filé de frango, Requeijão cremoso, Bacon, Queijo Mussarela e Salada',
                'value' => '17.00',
                'type_id' => 3,
                'active' => 0,
                'created_at' => '2023-02-04 23:12:01',
                'updated_at' => '2023-02-04 23:12:01',
            ),
            
            array (
                'id' => 15,
                'name' => 'Mr. Filé',
                'ingredients' => 'Pão, Filé de carne, Bacon, Hambúrguer, Presunto, Queijo e Salada',
                'value' => '21.00',
                'type_id' => 3,
                'active' => 0,
                'created_at' => '2023-02-04 23:12:01',
                'updated_at' => '2023-02-04 23:12:01',
            ),
            
            array (
                'id' => 16,
                'name' => 'Mr. Egg Bacon',
                'ingredients' => 'Pão, Bacon, Hambúrguer, Ovo, Queijo mussarela, Presunto, Queijo e Salada',
                'value' => '16.00',
                'type_id' => 3,
                'active' => 0,
                'created_at' => '2023-02-04 23:12:01',
                'updated_at' => '2023-02-04 23:12:01',
            ),
            
            array (
                'id' => 17,
                'name' => 'Americano Especial',
                'ingredients' => 'Pão, Ovo, Calabresa defumada, Queijo mussarela, Presunto e Salada',
                'value' => '15.00',
                'type_id' => 3,
                'active' => 0,
                'created_at' => '2023-02-04 23:12:01',
                'updated_at' => '2023-02-04 23:12:01',
            ),
            
            array (
                'id' => 18,
                'name' => 'Mr. Egg Burguer',
                'ingredients' => 'Pão, Salsicha, Hambúrguer, Ovo, Quejo mussarela e Salada',
                'value' => '15.00',
                'type_id' => 3,
                'active' => 0,
                'created_at' => '2023-02-04 23:12:01',
                'updated_at' => '2023-02-04 23:12:01',
            ),
            
            array (
                'id' => 19,
                'name' => 'Gourmet Suíno',
                'ingredients' => 'Pão com gegelim, 2 Hambúrgueres de 90g suíno, Molho barbecue, Queijo cheddar, Creme cheese, Banco, Tomate e Alface americano',
                'value' => '20.00',
                'type_id' => 3,
                'active' => 0,
                'created_at' => '2023-02-04 23:12:01',
                'updated_at' => '2023-02-04 23:12:01',
            ),
            
            array (
                'id' => 20,
                'name' => 'Mr. Topadão',
                'ingredients' => 'Pão, Filé de carne, Filé de frango, Bacon, Salsicha, Hambúrguer, Ovo, Calabresa, Presunto, Queijo mussarela e Salada',
                'value' => '27.00',
                'type_id' => 3,
                'active' => 0,
                'created_at' => '2023-02-04 23:12:01',
                'updated_at' => '2023-02-04 23:12:01',
            ),
            
            array (
                'id' => 21,
                'name' => 'Mr. Coração',
                'ingredients' => 'Pão, Coração de frango, Bacon, Queijo mussarela e salada',
                'value' => '21.00',
                'type_id' => 3,
                'active' => 0,
                'created_at' => '2023-02-04 23:12:01',
                'updated_at' => '2023-02-04 23:12:01',
            ),
            
            array (
                'id' => 22,
                'name' => 'Gourmet Bovino',
                'ingredients' => 'Pão com gergelim por cima, 2 Hambúrgueres de 90g bovino, Queijo cheddar, Tomate, Alface americano e creme cheese',
                'value' => '20.00',
                'type_id' => 3,
                'active' => 0,
                'created_at' => '2023-02-04 23:12:01',
                'updated_at' => '2023-02-04 23:12:01',
            ),
            
            array (
                'id' => 23,
                'name' => 'Mr. Frango',
                'ingredients' => 'Pão, Filé de frango, Requeijão cremoso, Bacon, Queijo Mussarela e Salada',
                'value' => '17.00',
                'type_id' => 3,
                'active' => 1,
                'created_at' => '2023-02-04 23:12:01',
                'updated_at' => '2023-02-04 23:12:01',
            ),
            
            array (
                'id' => 24,
                'name' => 'Mr. Filé',
                'ingredients' => 'Pão, Filé de carne, Bacon, Hambúrguer, Presunto, Queijo e Salada',
                'value' => '21.00',
                'type_id' => 3,
                'active' => 1,
                'created_at' => '2023-02-04 23:12:01',
                'updated_at' => '2023-02-04 23:12:01',
            ),
            
            array (
                'id' => 25,
                'name' => 'Mr. Egg Bacon',
                'ingredients' => 'Pão, Bacon, Hambúrguer, Ovo, Queijo mussarela, Presunto, Queijo e Salada',
                'value' => '16.00',
                'type_id' => 3,
                'active' => 1,
                'created_at' => '2023-02-04 23:12:01',
                'updated_at' => '2023-02-04 23:12:01',
            ),
            
            array (
                'id' => 26,
                'name' => 'Americano Especial',
                'ingredients' => 'Pão, Ovo, Calabresa defumada, Queijo mussarela, Presunto e Salada',
                'value' => '15.00',
                'type_id' => 3,
                'active' => 1,
                'created_at' => '2023-02-04 23:12:01',
                'updated_at' => '2023-02-04 23:12:01',
            ),
            
            array (
                'id' => 27,
                'name' => 'Mr. Egg Burguer',
                'ingredients' => 'Pão, Salsicha, Hambúrguer, Ovo, Quejo mussarela e Salada',
                'value' => '15.00',
                'type_id' => 3,
                'active' => 1,
                'created_at' => '2023-02-04 23:12:01',
                'updated_at' => '2023-02-04 23:12:01',
            ),
            
            array (
                'id' => 28,
                'name' => 'Gourmet Suíno',
                'ingredients' => 'Pão com gegelim, 2 Hambúrgueres de 90g suíno, Molho barbecue, Queijo cheddar, Creme cheese, Banco, Tomate e Alface americano',
                'value' => '20.00',
                'type_id' => 3,
                'active' => 1,
                'created_at' => '2023-02-04 23:12:01',
                'updated_at' => '2023-02-04 23:12:01',
            ),
            
            array (
                'id' => 29,
                'name' => 'Mr. Topadão',
                'ingredients' => 'Pão, Filé de carne, Filé de frango, Bacon, Salsicha, Hambúrguer, Ovo, Calabresa, Presunto, Queijo mussarela e Salada',
                'value' => '27.00',
                'type_id' => 3,
                'active' => 1,
                'created_at' => '2023-02-04 23:12:01',
                'updated_at' => '2023-02-04 23:12:01',
            ),
            
            array (
                'id' => 30,
                'name' => 'Mr. Coração',
                'ingredients' => 'Pão, Coração de frango, Bacon, Queijo mussarela e salada',
                'value' => '21.00',
                'type_id' => 3,
                'active' => 1,
                'created_at' => '2023-02-04 23:12:01',
                'updated_at' => '2023-02-04 23:12:01',
            ),
            
            array (
                'id' => 31,
                'name' => 'Gourmet Bovino',
                'ingredients' => 'Pão com gergelim por cima, 2 Hambúrgueres de 90g bovino, Queijo cheddar, Tomate, Alface americano e creme cheese',
                'value' => '20.00',
                'type_id' => 3,
                'active' => 1,
                'created_at' => '2023-02-04 23:12:01',
                'updated_at' => '2023-02-04 23:12:01',
            ),
            
            array (
                'id' => 32,
                'name' => 'Água Mineral c/gás',
                'ingredients' => '',
                'value' => '3.00',
                'type_id' => 4,
                'active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            
            array (
                'id' => 33,
                'name' => 'Água Mineral s/gás',
                'ingredients' => '',
                'value' => '2.50',
                'type_id' => 4,
                'active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            
            array (
                'id' => 34,
                'name' => 'Refrigerante Lata',
                'ingredients' => '',
                'value' => '5.00',
                'type_id' => 4,
                'active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            
            array (
                'id' => 35,
                'name' => 'Skinka',
                'ingredients' => '',
                'value' => '3.00',
                'type_id' => 4,
                'active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            
            array (
                'id' => 36,
                'name' => 'Refrigerante 1L',
                'ingredients' => '',
                'value' => '7.00',
                'type_id' => 4,
                'active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            
            array (
                'id' => 37,
                'name' => 'Redbull',
                'ingredients' => '',
                'value' => '10.00',
                'type_id' => 4,
                'active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            
            array (
                'id' => 38,
                'name' => 'Água Mineral c/gás',
                'ingredients' => '',
                'value' => '3.00',
                'type_id' => 4,
                'active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            
            array (
                'id' => 39,
                'name' => 'Água Mineral s/gás',
                'ingredients' => '',
                'value' => '2.50',
                'type_id' => 4,
                'active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            
            array (
                'id' => 40,
                'name' => 'Refrigerante Lata',
                'ingredients' => '',
                'value' => '5.00',
                'type_id' => 4,
                'active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            
            array (
                'id' => 41,
                'name' => 'Skinka',
                'ingredients' => '',
                'value' => '3.00',
                'type_id' => 4,
                'active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            
            array (
                'id' => 42,
                'name' => 'Refrigerante 1L',
                'ingredients' => '',
                'value' => '7.00',
                'type_id' => 4,
                'active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            
            array (
                'id' => 43,
                'name' => 'Redbull',
                'ingredients' => '',
                'value' => '10.00',
                'type_id' => 4,
                'active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            
            array (
                'id' => 52,
                'name' => 'Graviola',
                'ingredients' => '',
                'value' => '5.00',
                'type_id' => 6,
                'active' => 1,
                'created_at' => '2023-02-04 22:49:41',
                'updated_at' => '2023-02-04 22:49:41',
            ),
            
            array (
                'id' => 53,
                'name' => 'Laranja',
                'ingredients' => ',jbb',
                'value' => '6.00',
                'type_id' => 6,
                'active' => 1,
                'created_at' => '2023-02-04 22:49:41',
                'updated_at' => '2023-02-04 22:49:41',
            ),
            
            array (
                'id' => 54,
                'name' => 'Maracujá',
                'ingredients' => '',
                'value' => '6.00',
                'type_id' => 6,
                'active' => 1,
                'created_at' => '2023-02-04 22:49:41',
                'updated_at' => '2023-02-04 22:49:41',
            ),
            
            array (
                'id' => 55,
                'name' => 'Acerola',
                'ingredients' => '',
                'value' => '5.00',
                'type_id' => 6,
                'active' => 1,
                'created_at' => '2023-02-04 22:49:41',
                'updated_at' => '2023-02-04 22:49:41',
            ),
            
            array (
                'id' => 56,
                'name' => 'Cajá',
                'ingredients' => '',
                'value' => '5.00',
                'type_id' => 6,
                'active' => 1,
                'created_at' => '2023-02-04 22:49:41',
                'updated_at' => '2023-02-04 22:49:41',
            ),
            
            array (
                'id' => 57,
                'name' => 'Mangaba',
                'ingredients' => '',
                'value' => '5.00',
                'type_id' => 6,
                'active' => 1,
                'created_at' => '2023-02-04 22:49:41',
                'updated_at' => '2023-02-04 22:49:41',
            ),
            
            array (
                'id' => 58,
                'name' => 'Mangaba',
                'ingredients' => '',
                'value' => '5.00',
                'type_id' => 6,
                'active' => 1,
                'created_at' => '2023-02-04 22:49:41',
                'updated_at' => '2023-02-04 22:49:41',
            ),
            
            array (
                'id' => 59,
                'name' => 'Goiaba',
                'ingredients' => '',
                'value' => '5.00',
                'type_id' => 6,
                'active' => 1,
                'created_at' => '2023-02-04 22:49:41',
                'updated_at' => '2023-02-04 22:49:41',
            ),
            
            array (
                'id' => 60,
                'name' => 'Manga',
                'ingredients' => '',
                'value' => '5.00',
                'type_id' => 6,
                'active' => 1,
                'created_at' => '2023-02-04 22:49:41',
                'updated_at' => '2023-02-04 22:49:41',
            ),
            
            array (
                'id' => 71,
                'name' => 'Filé c/fritas',
                'ingredients' => 'bjb',
                'value' => '35.00',
                'type_id' => 5,
                'active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            
            array (
                'id' => 72,
                'name' => 'Batata Frita',
                'ingredients' => '',
                'value' => '15.00',
                'type_id' => 5,
                'active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            
            array (
                'id' => 73,
                'name' => 'Batata Frita Especial',
                'ingredients' => '',
                'value' => '20.00',
                'type_id' => 5,
                'active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            
            array (
                'id' => 79,
                'name' => 'Caju',
                'ingredients' => 'sxs',
                'value' => '5.00',
                'type_id' => 6,
                'active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            
            array (
                'id' => 80,
                'name' => 'Caçulinha',
                'ingredients' => 'hkfir',
                'value' => '2.50',
                'type_id' => 4,
                'active' => 1,
                'created_at' => '2023-04-02 21:45:48',
                'updated_at' => '2023-04-02 21:45:48',
            ),
            
            array (
                'id' => 5002,
                'name' => 'Pizza de Queijo M',
                'ingredients' => 'Molho De Tomate Caseiro, Queijo, Azeitona E Oregano',
                'value' => '30.00',
                'type_id' => 5001,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5003,
                'name' => 'Pizza de Frango Catupry G',
                'ingredients' => 'Molho De Tomate Caseiro, Frango, Muçarela, Catupiry, Azeitona E Oregano',
                'value' => '42.00',
                'type_id' => 5001,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5004,
                'name' => 'Pizza de Frango Catupry M',
                'ingredients' => 'Molho De Tomate Caseiro, Frango, Muçarela, Catupiry, Azeitona E Oregano',
                'value' => '31.00',
                'type_id' => 5001,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5005,
                'name' => 'Pizza de Frango G',
                'ingredients' => 'Molho De Tomate Caseiro, Frango, Muçarela, Azeitona E Oregano',
                'value' => '42.00',
                'type_id' => 5001,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5006,
                'name' => 'Pizza de Frango M',
                'ingredients' => 'Molho De Tomate Caseiro, Frango, Muçarela, Azeitona E Oregano',
                'value' => '31.00',
                'type_id' => 5001,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5007,
                'name' => 'Pizza de Frango Caipira G',
                'ingredients' => 'Molho De Tomate Caseiro, Frango, Muçarela, Milho Verde, Azeitona E Oregano',
                'value' => '42.00',
                'type_id' => 5001,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5008,
                'name' => 'Pizza de Frango Caipira M',
                'ingredients' => 'Molho De Tomate Caseiro, Frango, Muçarela, Milho Verde, Azeitona E Oregano',
                'value' => '31.00',
                'type_id' => 5001,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5009,
                'name' => 'Pizza de Portuguesa G',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Calabresa, Presunto, Ovos, Cebola, Pimentão, Oregano E Azeitona',
                'value' => '40.00',
                'type_id' => 5001,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5010,
                'name' => 'Pizza de Portuguesa M',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Calabresa, Presunto, Ovos, Cebola, Pimentão, Oregano E Azeitona',
                'value' => '30.00',
                'type_id' => 5001,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5011,
                'name' => 'Pizza de Calabresa G',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Calabresa, Cebola Oregano E Azeitona',
                'value' => '42.00',
                'type_id' => 5001,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5012,
                'name' => 'Pizza de Calabresa M',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Calabresa, Cebola Oregano E Azeitona',
                'value' => '32.00',
                'type_id' => 5001,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5013,
                'name' => 'Pizza de 4 Queijos G',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Cheddar, Catupiry, Queijo Qualho, Oregano E Azeitona',
                'value' => '42.00',
                'type_id' => 5002,
                'active' => 0,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5014,
                'name' => 'Pizza de 4 Queijos M',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Cheddar, Catupiry, Queijo Qualho, Oregano E Azeitona',
                'value' => '32.00',
                'type_id' => 5002,
                'active' => 0,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5015,
                'name' => 'Pizza de Frango Com Bacon G',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Bacon, Oregano E Azeitona',
                'value' => '42.00',
                'type_id' => 5002,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5016,
                'name' => 'Pizza de Frango Com Bacon M',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Bacon, Oregano E Azeitona',
                'value' => '32.00',
                'type_id' => 5002,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5017,
                'name' => 'Pizza De Filé G',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Contra Filé Com Catupiry E Doritos',
                'value' => '46.00',
                'type_id' => 5002,
                'active' => 0,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5018,
                'name' => 'Pizza De Filé M',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Contra Filé Com Catupiry E Doritos',
                'value' => '36.00',
                'type_id' => 5002,
                'active' => 0,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5019,
                'name' => 'Pizza de Atum G',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Atum, Cebola, Pimentão, Azeitona E Oregano',
                'value' => '44.00',
                'type_id' => 5002,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5020,
                'name' => 'Pizza de Atum M',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Atum, Cebola, Pimentão, Azeitona E Oregano',
                'value' => '34.00',
                'type_id' => 5002,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5021,
                'name' => 'Pizza de Charque G',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Charque, Queijo Qualho, Cebola, Oregano E Azeitona',
                'value' => '46.00',
                'type_id' => 5002,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5022,
                'name' => 'Pizza de Charque M',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Charque, Queijo Qualho, Cebola, Oregano E Azeitona',
                'value' => '36.00',
                'type_id' => 5002,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5023,
                'name' => 'Pizza de Camarão Com Catupiry G',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Camarão, Catupiry, Cebola, Oregano E Azeitona',
                'value' => '50.00',
                'type_id' => 5002,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5024,
                'name' => 'Pizza de Camarão Com Catupiry M',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Camarão, Catupiry, Cebola, Oregano E Azeitona',
                'value' => '40.00',
                'type_id' => 5002,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5025,
                'name' => 'Pizza de Carne De Sol G',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Carne De Sol Desfiada, Com Catupiry, Oregano E Azeitona',
                'value' => '20.00',
                'type_id' => 5002,
                'active' => 0,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5026,
                'name' => 'Pizza de Carne De Sol M',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Carne De Sol Desfiada, Com Catupiry, Oregano E Azeitona',
                'value' => '20.00',
                'type_id' => 5002,
                'active' => 0,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5027,
                'name' => 'Pizza de Baiana G',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Calabresa Moída, Pimenta Calabresa, Pimentão, Oregano E Azeitona',
                'value' => '42.00',
                'type_id' => 5002,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5028,
                'name' => 'Pizza de Baiana M',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Calabresa Moída, Pimenta Calabresa, Pimentão, Oregano E Azeitona',
                'value' => '32.00',
                'type_id' => 5002,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5029,
                'name' => 'Pizza Romeu E Julieta G',
                'ingredients' => 'Goiabada Cremosa E Queijo Qualho',
                'value' => '41.00',
                'type_id' => 5003,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5030,
                'name' => 'Pizza Romeu E Julieta M',
                'ingredients' => 'Goiabada Cremosa E Queijo Qualho',
                'value' => '31.00',
                'type_id' => 5003,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5031,
                'name' => 'Pizza de Farinha Lactea G',
                'ingredients' => 'Chocolate Branco Com Farinha Lactea',
                'value' => '41.00',
                'type_id' => 5003,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5032,
                'name' => 'Pizza de Farinha Lactea M',
                'ingredients' => 'Chocolate Branco Com Farinha Lactea',
                'value' => '31.00',
                'type_id' => 5003,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5033,
                'name' => 'Pizza de Disquete G',
                'ingredients' => 'Chocolate Ao Leite Com Disquete',
                'value' => '41.00',
                'type_id' => 5003,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5034,
                'name' => 'Pizza de Disquete M',
                'ingredients' => 'Chocolate Ao Leite Com Disquete',
                'value' => '31.00',
                'type_id' => 5003,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5035,
                'name' => 'Pizza de Kitkat G',
                'ingredients' => 'Chocolate Ao Leite Com Kitkat',
                'value' => '41.00',
                'type_id' => 5003,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5036,
                'name' => 'Pizza de Kitkat M',
                'ingredients' => 'Chocolate Ao Leite Com Kitkat',
                'value' => '31.00',
                'type_id' => 5003,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5037,
                'name' => 'Pizza Cartola G',
                'ingredients' => 'Queijo Muçarela, Banana, Leite Condençado E Canela Em Pó',
                'value' => '41.00',
                'type_id' => 5003,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5038,
                'name' => 'Pizza Cartola M',
                'ingredients' => 'Queijo Muçarela, Banana, Leite Condençado E Canela Em Pó',
                'value' => '31.00',
                'type_id' => 5003,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5039,
                'name' => 'Macarronada De Carne Moída',
                'ingredients' => 'Carne Moída',
                'value' => '19.00',
                'type_id' => 5006,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5040,
                'name' => 'Macarronada De Contra Filé',
                'ingredients' => 'Contra Filé',
                'value' => '25.00',
                'type_id' => 5006,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5041,
                'name' => 'Macarronada De Frango',
                'ingredients' => 'Frango',
                'value' => '19.00',
                'type_id' => 5006,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5042,
                'name' => 'Macarronada De Calabresa',
                'ingredients' => 'Calabresa',
                'value' => '19.00',
                'type_id' => 5006,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5043,
                'name' => 'Macarronada De Camarão',
                'ingredients' => 'Camarão',
                'value' => '25.00',
                'type_id' => 5006,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5044,
                'name' => 'Contra Filé Com Batata',
                'ingredients' => 'Contra Filé, Batata',
                'value' => '35.00',
                'type_id' => 5007,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5045,
                'name' => 'Calabresa Acebolada',
                'ingredients' => 'Calabresa, Cebola',
                'value' => '25.00',
                'type_id' => 5007,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5046,
                'name' => 'Camarão À Dorê',
                'ingredients' => 'Camarão',
                'value' => '35.00',
                'type_id' => 5007,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5047,
                'name' => 'Porção De Batata Frita',
                'ingredients' => 'Batata Frita',
                'value' => '17.00',
                'type_id' => 5007,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5048,
                'name' => 'Batata Especial',
                'ingredients' => 'Requeijão Cheddar, Bacon E Queijo Ralado',
                'value' => '22.00',
                'type_id' => 5007,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5049,
                'name' => 'Caldinho Do Dia',
                'ingredients' => 'Sugestão Do Chefe',
                'value' => '10.00',
                'type_id' => 5007,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5050,
                'name' => 'Porção Com 12 Coxinha Da Asa',
                'ingredients' => 'Coxinha De Frango',
                'value' => '25.00',
                'type_id' => 5007,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5051,
                'name' => 'Batata Suiça De Pizza',
                'ingredients' => 'Batata Inglesa, Presunto, Queijo, Requeijão Cremoso, Oregano E Tomate',
                'value' => '25.00',
                'type_id' => 5008,
                'active' => 1,
                'created_at' => '2023-02-06 04:43:57',
                'updated_at' => '2023-02-06 04:43:57',
            ),
            
            array (
                'id' => 5052,
                'name' => 'Batata Suiça De Frango',
                'ingredients' => 'Batata Inglesa, Frango Desfiado E Requeijão Cremoso',
                'value' => '25.00',
                'type_id' => 5008,
                'active' => 1,
                'created_at' => '2023-02-07 04:43:57',
                'updated_at' => '2023-04-24 22:26:03',
            ),
            
            array (
                'id' => 5053,
                'name' => 'Batata Suiça De Calabresa',
                'ingredients' => 'Batata Inglesa, Calabresa Defumada E Requeijão Cremoso',
                'value' => '25.00',
                'type_id' => 5008,
                'active' => 1,
                'created_at' => '2023-02-08 04:43:57',
                'updated_at' => '2023-02-08 04:43:57',
            ),
            
            array (
                'id' => 5054,
                'name' => 'Batata Suiça De Contra Filé',
                'ingredients' => 'Batata Inglesa, Contra Filé E Requeijão Cremoso',
                'value' => '30.00',
                'type_id' => 5008,
                'active' => 1,
                'created_at' => '2023-02-09 04:43:57',
                'updated_at' => '2023-02-09 04:43:57',
            ),
            
            array (
                'id' => 5055,
                'name' => 'Batata Suiça De Camarão',
                'ingredients' => 'Batata Inglesa, Camarão E Requeijão Cremoso',
                'value' => '30.00',
                'type_id' => 5008,
                'active' => 1,
                'created_at' => '2023-02-10 04:43:57',
                'updated_at' => '2023-02-10 04:43:57',
            ),
            
            array (
                'id' => 5056,
                'name' => 'Laranja',
                'ingredients' => 'Laranja',
                'value' => '6.00',
                'type_id' => 5009,
                'active' => 1,
                'created_at' => '2023-02-08 04:43:57',
                'updated_at' => '2023-02-08 04:43:57',
            ),
            
            array (
                'id' => 5057,
                'name' => 'Acerola',
                'ingredients' => 'Acerola',
                'value' => '5.00',
                'type_id' => 5009,
                'active' => 1,
                'created_at' => '2023-02-09 04:43:57',
                'updated_at' => '2023-02-09 04:43:57',
            ),
            
            array (
                'id' => 5058,
                'name' => 'Graviola',
                'ingredients' => 'Graviola',
                'value' => '5.00',
                'type_id' => 5009,
                'active' => 1,
                'created_at' => '2023-02-10 04:43:57',
                'updated_at' => '2023-02-10 04:43:57',
            ),
            
            array (
                'id' => 5059,
                'name' => 'Goiaba',
                'ingredients' => 'Goiaba',
                'value' => '5.00',
                'type_id' => 5009,
                'active' => 1,
                'created_at' => '2023-02-08 04:43:57',
                'updated_at' => '2023-02-08 04:43:57',
            ),
            
            array (
                'id' => 5060,
                'name' => 'Maracujá',
                'ingredients' => 'Maracujá',
                'value' => '5.00',
                'type_id' => 5009,
                'active' => 1,
                'created_at' => '2023-02-09 04:43:57',
                'updated_at' => '2023-02-09 04:43:57',
            ),
            
            array (
                'id' => 5061,
                'name' => 'Cajú',
                'ingredients' => 'Cajú',
                'value' => '5.00',
                'type_id' => 5009,
                'active' => 1,
                'created_at' => '2023-02-10 04:43:57',
                'updated_at' => '2023-02-10 04:43:57',
            ),
            
            array (
                'id' => 5062,
                'name' => 'Manga',
                'ingredients' => 'Manga',
                'value' => '5.00',
                'type_id' => 5009,
                'active' => 1,
                'created_at' => '2023-02-08 04:43:57',
                'updated_at' => '2023-02-08 04:43:57',
            ),
            
            array (
                'id' => 5063,
                'name' => 'Cajá',
                'ingredients' => 'Cajá',
                'value' => '5.00',
                'type_id' => 5009,
                'active' => 1,
                'created_at' => '2023-02-08 04:43:57',
                'updated_at' => '2023-02-08 04:43:57',
            ),
            
            array (
                'id' => 5064,
                'name' => 'Tamarindo',
                'ingredients' => 'Tamarindo',
                'value' => '5.00',
                'type_id' => 5009,
                'active' => 1,
                'created_at' => '2023-02-09 04:43:57',
                'updated_at' => '2023-02-09 04:43:57',
            ),
            
            array (
                'id' => 5065,
                'name' => 'Abacaxi com Hortelã',
                'ingredients' => 'Abacaxi com Hortelã',
                'value' => '5.00',
                'type_id' => 5009,
                'active' => 1,
                'created_at' => '2023-02-10 04:43:57',
                'updated_at' => '2023-02-10 04:43:57',
            ),
            
            array (
                'id' => 5066,
                'name' => 'Água com Gás',
                'ingredients' => 'Água com Gás',
                'value' => '3.00',
                'type_id' => 5010,
                'active' => 1,
                'created_at' => '2023-02-11 04:43:57',
                'updated_at' => '2023-02-11 04:43:57',
            ),
            
            array (
                'id' => 5067,
                'name' => 'Água sem Gás',
                'ingredients' => 'Água sem Gás',
                'value' => '2.50',
                'type_id' => 5010,
                'active' => 1,
                'created_at' => '2023-02-12 04:43:57',
                'updated_at' => '2023-02-12 04:43:57',
            ),
            
            array (
                'id' => 5068,
                'name' => 'Balde com 4 Long Neck Budweiser',
                'ingredients' => 'Balde com 4 Long Neck Budweiser',
                'value' => '30.00',
                'type_id' => 5010,
                'active' => 1,
                'created_at' => '2023-02-13 04:43:57',
                'updated_at' => '2023-02-13 04:43:57',
            ),
            
            array (
                'id' => 5069,
                'name' => 'Balde com 4 Long Neck Heineken',
                'ingredients' => 'Balde com 4 Long Neck Heineken',
                'value' => '35.00',
                'type_id' => 5010,
                'active' => 1,
                'created_at' => '2023-02-14 04:43:57',
                'updated_at' => '2023-02-14 04:43:57',
            ),
            
            array (
                'id' => 5070,
                'name' => 'Balde com 4 Long Neck Corona',
                'ingredients' => 'Balde com 4 Long Neck Corona',
                'value' => '0.00',
                'type_id' => 5010,
                'active' => 0,
                'created_at' => '2023-02-15 04:43:57',
                'updated_at' => '2023-02-15 04:43:57',
            ),
            
            array (
                'id' => 5071,
                'name' => 'Refrigerante 1L Pet',
                'ingredients' => 'Refrigerante 1L Pet',
                'value' => '8.00',
                'type_id' => 5010,
                'active' => 1,
                'created_at' => '2023-02-16 04:43:57',
                'updated_at' => '2023-02-16 04:43:57',
            ),
            
            array (
                'id' => 5072,
                'name' => 'Refrigerante 1L LS',
                'ingredients' => 'Refrigerante 1L LS',
                'value' => '8.00',
                'type_id' => 5010,
                'active' => 1,
                'created_at' => '2023-02-17 04:43:57',
                'updated_at' => '2023-02-17 04:43:57',
            ),
            
            array (
                'id' => 5073,
                'name' => 'Refrigerante Latinha',
                'ingredients' => 'Refrigerante Latinha',
                'value' => '5.00',
                'type_id' => 5010,
                'active' => 1,
                'created_at' => '2023-02-17 04:43:57',
                'updated_at' => '2023-02-17 04:43:57',
            ),
            
            array (
                'id' => 5074,
                'name' => 'Meia/ Pizza de Queijo G',
                'ingredients' => 'Molho De Tomate Caseiro, Queijo, Azeitona E Oregano',
                'value' => '40.00',
                'type_id' => 5004,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5075,
                'name' => 'Meia/Pizza de Queijo M',
                'ingredients' => 'Molho De Tomate Caseiro, Queijo, Azeitona E Oregano',
                'value' => '30.00',
                'type_id' => 5005,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5076,
                'name' => 'Meia/Pizza de Frango Catupiry G',
                'ingredients' => 'Molho De Tomate Caseiro, Frango, Muçarela, Catupiry, Azeitona E Oregano',
                'value' => '42.00',
                'type_id' => 5004,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5077,
                'name' => 'Meia/Pizza de Frango Catupiry M',
                'ingredients' => 'Molho De Tomate Caseiro, Frango, Muçarela, Catupiry, Azeitona E Oregano',
                'value' => '31.00',
                'type_id' => 5005,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5078,
                'name' => 'Meia/Pizza de Frango G',
                'ingredients' => 'Molho De Tomate Caseiro, Frango, Muçarela, Azeitona E Oregano',
                'value' => '42.00',
                'type_id' => 5004,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5079,
                'name' => 'Meia/Pizza de Frango M',
                'ingredients' => 'Molho De Tomate Caseiro, Frango, Muçarela, Azeitona E Oregano',
                'value' => '31.00',
                'type_id' => 5005,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5080,
                'name' => 'Meia/Pizza de Frango Caipira G',
                'ingredients' => 'Molho De Tomate Caseiro, Frango, Muçarela, Milho Verde, Azeitona E Oregano',
                'value' => '42.00',
                'type_id' => 5004,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5081,
                'name' => 'Meia/Pizza de Frango Caipira M',
                'ingredients' => 'Molho De Tomate Caseiro, Frango, Muçarela, Milho Verde, Azeitona E Oregano',
                'value' => '31.00',
                'type_id' => 5005,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5082,
                'name' => 'Meia/Pizza de Portuguesa G',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Calabresa, Presunto, Ovos, Cebola, Pimentão, Oregano E Azeitona',
                'value' => '40.00',
                'type_id' => 5004,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5083,
                'name' => 'Meia/Pizza de Portuguesa M',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Calabresa, Presunto, Ovos, Cebola, Pimentão, Oregano E Azeitona',
                'value' => '30.00',
                'type_id' => 5005,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5084,
                'name' => 'Meia/Pizza de Calabresa G',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Calabresa, Cebola Oregano E Azeitona',
                'value' => '42.00',
                'type_id' => 5004,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5085,
                'name' => 'Meia/Pizza de Calabresa M',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Calabresa, Cebola Oregano E Azeitona',
                'value' => '32.00',
                'type_id' => 5005,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5086,
                'name' => 'Pizza de 4 Queijos G',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Cheddar, Catupiry, Queijo Qualho, Oregano E Azeitona',
                'value' => '42.00',
                'type_id' => 5002,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5087,
                'name' => 'Pizza de 4 Queijos M',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Cheddar, Catupiry, Queijo Qualho, Oregano E Azeitona',
                'value' => '32.00',
                'type_id' => 5002,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5088,
                'name' => 'Pizza de Frango Com Bacon G',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Bacon, Oregano E Azeitona',
                'value' => '42.00',
                'type_id' => 5002,
                'active' => 0,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5089,
                'name' => 'Pizza de Frango Com Bacon M',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Bacon, Oregano E Azeitona',
                'value' => '32.00',
                'type_id' => 5002,
                'active' => 0,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5090,
                'name' => 'Pizza De Filé G',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Contra Filé Com Catupiry E Doritos',
                'value' => '46.00',
                'type_id' => 5002,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5091,
                'name' => 'Pizza De Filé M',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Contra Filé Com Catupiry E Doritos',
                'value' => '36.00',
                'type_id' => 5002,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5092,
                'name' => 'Meia/Pizza de Atum G',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Atum, Cebola, Pimentão, Azeitona E Oregano',
                'value' => '44.00',
                'type_id' => 5004,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5093,
                'name' => 'Meia/Pizza de Atum M',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Atum, Cebola, Pimentão, Azeitona E Oregano',
                'value' => '34.00',
                'type_id' => 5005,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5094,
                'name' => 'Meia/Pizza de Charque G',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Charque, Queijo Qualho, Cebola, Oregano E Azeitona',
                'value' => '46.00',
                'type_id' => 5004,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5095,
                'name' => 'Meia/Pizza de Charque M',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Charque, Queijo Qualho, Cebola, Oregano E Azeitona',
                'value' => '36.00',
                'type_id' => 5005,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5096,
                'name' => 'Meia/Pizza de Camarão Com Catupiry G',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Camarão, Catupiry, Cebola, Oregano E Azeitona',
                'value' => '50.00',
                'type_id' => 5004,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5097,
                'name' => 'Meia/Pizza de Camarão Com Catupiry M',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Camarão, Catupiry, Cebola, Oregano E Azeitona',
                'value' => '40.00',
                'type_id' => 5005,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5098,
                'name' => 'Meia/Pizza de Carne De Sol G',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Carne De Sol Desfiada, Com Catupiry, Oregano E Azeitona',
                'value' => '20.00',
                'type_id' => 5004,
                'active' => 0,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5099,
                'name' => 'Meia/Pizza de Carne De Sol M',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Carne De Sol Desfiada, Com Catupiry, Oregano E Azeitona',
                'value' => '20.00',
                'type_id' => 5005,
                'active' => 0,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5100,
                'name' => 'Meia/Pizza de Baiana G',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Calabresa Moída, Pimenta Calabresa, Pimentão, Oregano E Azeitona',
                'value' => '42.00',
                'type_id' => 5004,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5101,
                'name' => 'Meia/Pizza de Baiana M',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Calabresa Moída, Pimenta Calabresa, Pimentão, Oregano E Azeitona',
                'value' => '32.00',
                'type_id' => 5005,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5102,
                'name' => 'Meia/Pizza Romeu E Julieta G',
                'ingredients' => 'Goiabada Cremosa E Queijo Qualho',
                'value' => '41.00',
                'type_id' => 5004,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5103,
                'name' => 'Meia/Pizza Romeu E Julieta M',
                'ingredients' => 'Goiabada Cremosa E Queijo Qualho',
                'value' => '31.00',
                'type_id' => 5005,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5104,
                'name' => 'Meia/Pizza de Farinha Lactea G',
                'ingredients' => 'Chocolate Branco Com Farinha Lactea',
                'value' => '41.00',
                'type_id' => 5004,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5105,
                'name' => 'Meia/Pizza de Farinha Lactea M',
                'ingredients' => 'Chocolate Branco Com Farinha Lactea',
                'value' => '31.00',
                'type_id' => 5005,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5106,
                'name' => 'Meia/Pizza de Disquete G',
                'ingredients' => 'Chocolate Ao Leite Com Disquete',
                'value' => '41.00',
                'type_id' => 5004,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5107,
                'name' => 'Meia/Pizza de Disquete M',
                'ingredients' => 'Chocolate Ao Leite Com Disquete',
                'value' => '31.00',
                'type_id' => 5005,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5108,
                'name' => 'Meia/Pizza de Kitkat G',
                'ingredients' => 'Chocolate Ao Leite Com Kitkat',
                'value' => '41.00',
                'type_id' => 5004,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5109,
                'name' => 'Meia/Pizza de Kitkat M',
                'ingredients' => 'Chocolate Ao Leite Com Kitkat',
                'value' => '31.00',
                'type_id' => 5005,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5110,
                'name' => 'Meia/Pizza Cartola G',
                'ingredients' => 'Queijo Muçarela, Banana, Leite Condençado E Canela Em Pó',
                'value' => '41.00',
                'type_id' => 5004,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5111,
                'name' => 'Meia/Pizza Cartola M',
                'ingredients' => 'Queijo Muçarela, Banana, Leite Condençado E Canela Em Pó',
                'value' => '31.00',
                'type_id' => 5005,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5112,
                'name' => 'Meia/Pizza De Filé G',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Contra Filé Com Catupiry E Doritos',
                'value' => '46.00',
                'type_id' => 5004,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5113,
                'name' => 'Meia/Pizza De Filé M',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Contra Filé Com Catupiry E Doritos',
                'value' => '36.00',
                'type_id' => 5005,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5114,
                'name' => 'Meia/Pizza de Frango Com Bacon G',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Bacon, Oregano E Azeitona',
                'value' => '42.00',
                'type_id' => 5004,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5115,
                'name' => 'Meia/Pizza de Frango Com Bacon M',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Bacon, Oregano E Azeitona',
                'value' => '32.00',
                'type_id' => 5005,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5116,
                'name' => 'Meia/Pizza de 4 Queijos G',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Cheddar, Catupiry, Queijo Qualho, Oregano E Azeitona',
                'value' => '42.00',
                'type_id' => 5004,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 5117,
                'name' => 'Meia/Pizza de 4 Queijos M',
                'ingredients' => 'Molho De Tomate Caseiro, Muçarela, Cheddar, Catupiry, Queijo Qualho, Oregano E Azeitona',
                'value' => '32.00',
                'type_id' => 5005,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 6000,
                'name' => 'Pina Colada',
                'ingredients' => 'Pina Colada',
                'value' => '18.00',
                'type_id' => 5010,
                'active' => 1,
                'created_at' => '2023-02-17 04:43:57',
                'updated_at' => '2023-02-17 04:43:57',
            ),
            
            array (
                'id' => 6001,
                'name' => 'Crepúsculo',
                'ingredients' => 'Crepúsculo',
                'value' => '16.00',
                'type_id' => 5010,
                'active' => 1,
                'created_at' => '2023-02-17 04:43:57',
                'updated_at' => '2023-02-17 04:43:57',
            ),
            
            array (
                'id' => 6002,
                'name' => 'Paradise',
                'ingredients' => 'Paradise',
                'value' => '20.00',
                'type_id' => 5010,
                'active' => 1,
                'created_at' => '2023-02-17 04:43:57',
                'updated_at' => '2023-02-17 04:43:57',
            ),
            
            array (
                'id' => 6003,
                'name' => 'Caipirinha',
                'ingredients' => 'Caipirinha',
                'value' => '10.00',
                'type_id' => 5010,
                'active' => 1,
                'created_at' => '2023-02-17 04:43:57',
                'updated_at' => '2023-02-17 04:43:57',
            ),
            
            array (
                'id' => 6004,
                'name' => 'ICE',
                'ingredients' => 'ICE',
                'value' => '10.00',
                'type_id' => 5010,
                'active' => 1,
                'created_at' => '2023-02-17 04:43:57',
                'updated_at' => '2023-02-17 04:43:57',
            ),
            
            array (
                'id' => 7000,
                'name' => 'Meia',
                'ingredients' => 'Meia',
                'value' => '0.00',
                'type_id' => 5004,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 7001,
                'name' => 'Cerveja Heineken',
                'ingredients' => 'Cerveja',
                'value' => '10.00',
                'type_id' => 5010,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 7002,
                'name' => 'Cerveja Budweiser',
                'ingredients' => 'Cerveja',
                'value' => '8.50',
                'type_id' => 5010,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 7003,
                'name' => 'Pirulito',
                'ingredients' => 'Pirulito',
                'value' => '0.25',
                'type_id' => 5012,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 7004,
                'name' => 'Caçulinha',
                'ingredients' => 'Caçulinha',
                'value' => '2.50',
                'type_id' => 5010,
                'active' => 1,
                'created_at' => '2023-02-17 04:43:57',
                'updated_at' => '2023-02-17 04:43:57',
            ),
            
            array (
                'id' => 7005,
                'name' => 'Embalagem',
                'ingredients' => 'Embalagem pra viagem',
                'value' => '1.00',
                'type_id' => 5011,
                'active' => 1,
                'created_at' => '2023-02-05 04:43:57',
                'updated_at' => '2023-02-05 04:43:57',
            ),
            
            array (
                'id' => 7006,
                'name' => 'redbull',
                'ingredients' => 'redbull',
                'value' => '12.00',
                'type_id' => 5010,
                'active' => 1,
                'created_at' => '2023-02-24 20:26:06',
                'updated_at' => '2023-02-24 20:26:06',
            ),
            
            array (
                'id' => 7009,
                'name' => 'Coca-zero',
                'ingredients' => 'Coca',
                'value' => '6.50',
                'type_id' => 5010,
                'active' => 1,
                'created_at' => '2023-03-11 18:59:33',
                'updated_at' => '2023-03-11 18:59:33',
            ),
            
            array (
                'id' => 7010,
                'name' => 'Caipifruta',
                'ingredients' => 'Caipifruta',
                'value' => '14.00',
                'type_id' => 5010,
                'active' => 1,
                'created_at' => '2023-03-11 20:55:51',
                'updated_at' => '2023-03-11 20:55:51',
            ),
            
            array (
                'id' => 7011,
                'name' => 'Pergola',
                'ingredients' => 'Vinho',
                'value' => '23.00',
                'type_id' => 5010,
                'active' => 1,
                'created_at' => '2023-03-26 22:53:23',
                'updated_at' => '2023-03-26 22:53:23',
            ),
            
            array (
                'id' => 7012,
                'name' => 'Pergola',
                'ingredients' => 'Vinho',
                'value' => '23.00',
                'type_id' => 5010,
                'active' => 1,
                'created_at' => '2023-03-26 22:53:23',
                'updated_at' => '2023-03-26 22:53:23',
            ),
            
            array (
                'id' => 7013,
                'name' => 'Original',
                'ingredients' => 'cerveja',
                'value' => '5.00',
                'type_id' => 5010,
                'active' => 1,
                'created_at' => '2023-03-28 22:16:08',
                'updated_at' => '2023-03-28 22:16:08',
            ),
            
            array (
                'id' => 7014,
                'name' => 'Skol PURO MALTE',
                'ingredients' => 'Skol PURO MALTE',
                'value' => '8.50',
                'type_id' => 5010,
                'active' => 1,
                'created_at' => '2023-04-01 18:22:57',
                'updated_at' => '2023-04-01 18:22:57',
            ),
            
            array (
                'id' => 7015,
                'name' => 'Balde com 4 Long Neck Skol PURO MALTE',
                'ingredients' => 'Cerverja',
                'value' => '30.00',
                'type_id' => 5010,
                'active' => 1,
                'created_at' => '2023-04-01 18:24:18',
                'updated_at' => '2023-04-01 18:24:18',
            ),
            
            array (
                'id' => 7016,
                'name' => 'Original',
                'ingredients' => 'cerveja',
                'value' => '6.00',
                'type_id' => 5010,
                'active' => 1,
                'created_at' => '2023-04-02 21:07:08',
                'updated_at' => '2023-04-02 21:07:08',
            ),
            
            array (
                'id' => 7017,
                'name' => 'Original',
                'ingredients' => 'cerveja',
                'value' => '6.00',
                'type_id' => 5010,
                'active' => 1,
                'created_at' => '2023-04-02 21:07:08',
                'updated_at' => '2023-04-02 21:07:08',
            ),
            
            array (
                'id' => 7018,
                'name' => 'dose',
                'ingredients' => 'dose',
                'value' => '3.00',
                'type_id' => 5010,
                'active' => 1,
                'created_at' => '2023-04-16 20:14:33',
                'updated_at' => '2023-04-16 20:14:33',
            ),
            
            array (
                'id' => 7020,
                'name' => 'Taça de vinho',
                'ingredients' => 'Vinho',
                'value' => '7.00',
                'type_id' => 5010,
                'active' => 1,
                'created_at' => '2023-04-25 20:38:14',
                'updated_at' => '2023-04-25 20:38:14',
            ),
            
            array (
                'id' => 10000,
                'name' => 'Taxa de entrega',
                'ingredients' => 'Nada',
                'value' => '2.00',
                'type_id' => 8,
                'active' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}